film/film/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

film/movieapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.detail,name="detail"),
    path('add/',views.add_movie,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

film/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

film/movieapp/forms.py
from django import forms
from .  models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields = ['name','desc','year','img']

film/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
    movie = Movie.objects.all
    context = {
        'movie_list': movie
    }
    return render(request, "index.html", context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')

    return render(request, 'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return  render(request,'delete.html')

film/templates/add.html
{% extends 'base.html' %}
{% block body %}


<form method="POST" action="{% url 'movieapp:add' %}" enctype="multipart/form-data" >
      {% csrf_token %}
      <input type="text" name="name" placeholder="Enter your movie name">
      <input type="text" name="desc" placeholder="Enter the movie description">
      <input type="text" name="year" placeholder="Enter the movie year">
      <input type="file" name="img">
<input type="submit">
</form>
{% endblock %}

film/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
<!--      <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">-->
      CineMagic
    </a>
    <a class= "btn btn-warning" href="{% url 'movieapp:add' %}">Add Movie</a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

film/templates/delete.html
<form method="post">
  {% csrf_token %}
  Are you sure to delete this movie
<input type="submit">
</form>

film/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="350" height="350"><br>
        </div>
<div class="col-md-6">
  <h1>{{movie.name}}</h1>
  <h3>{{movie.desc}}</h3>
  <h5>{{movie.year}}</h5>
    <a class= "btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
    <a class= "btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
</div>




   </div>
</div>
{% endblock %}

film/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

film/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3" style="margin-top:30px;">
            <div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." width="350px" height="400px" >
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Book Tickets</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}